# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!
platform :ios, '8.0'

#disable some warnings
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #disable some warnings of Pods
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end

workspace 'ArcIMTest'
target 'ArcIMTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcIMTest

   pod 'YYModel' 

end

 target 'MoudleOne' do 
  project 'Module/MoudleOne/MoudleOne.xcodeproj' 
    pod 'AFNetworking'
    pod 'YYModel' 
  end


 target 'MoudleTwo' do 
  project 'Module/MoudleTwo/MoudleTwo.xcodeproj' 
    pod 'YYModel' 
  end


target 'ArcIMTestBundle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArcIMTestBundle

end
